remote_theme: pmarsceill/just-the-docs

kramdown:
  typographic_symbols:
    ndash: __

# Aux links for the upper right navigation
aux_links:
  "grate on GitHub":
    - "//github.com/grate-devs/grate"
